---
# We expect, on the local ansible-playbook runner, a yaml containing
# the pull secret. The yaml is included a vars for ansible-microhsift-role
- name: Read file with openshift_pull_secret
  ansible.builtin.include_vars:
    file: "{{ pull_secret_path }}"
  no_log: true
  delegate_to: localhost

- name: "Install microshift on {{ ansible_host }}"
  ansible.builtin.include_role:
    name: "{{ ansible_microshift_role_dir }}"

- name: Check sf namespace exists on microshift
  become: true
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /var/lib/microshift/resources/kubeadmin/{{ inventory_hostname }}/kubeconfig get namespace sf
  register: sf_namespace
  failed_when: false
  changed_when: false

- name: Create sf namespace on microshift
  become: true
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /var/lib/microshift/resources/kubeadmin/{{ inventory_hostname }}/kubeconfig create namespace sf
  when: sf_namespace.rc != 0
