#!/bin/env python3
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


"""This script creates a package file from a directory file list
"""

import os
import sys

all = list(sorted(filter(lambda x: x.endswith(".dhall"),
                         os.listdir(sys.argv[1]))))

base = "./" + os.path.basename(sys.argv[1].rstrip('/')) + "/"

print("\n".join([
    "{- This file is generated by the '%s' script -}" % __file__,
    "{ ",
    " , ".join(map(lambda x: x.replace(".dhall", "") + " = " + base + x,
                   all)),
    " }"
]))
