#!/bin/env python
# A little script to generate per-user kubeconfig

import yaml, os, sys, socket, subprocess

try:
    namespace = sys.argv[1]
except:
    print("usage: create-kubeconfig <namespace-name>")
    exit(1)

subprocess.run(f"kubectl create namespace {namespace} > /dev/null", shell=True, check=True)
host_ip = socket.gethostbyname(socket.gethostname())
kubeconfig = yaml.safe_load(open("/root/.kube/config").read())
kubeconfig["clusters"][0]["cluster"]["server"] = f"https://{host_ip}:6443"
kubeconfig["contexts"][0]["context"]["namespace"] = namespace
print(yaml.dump(kubeconfig, default_flow_style=False))
