{
 "title": "AFS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "afs01.dfw /vicepa used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(divideSeries(stats.gauges.afs.afs01_dfw_openstack_org.part.vicepa.used, #A), 100)"
    }
   ]
  },
  {
   "title": "afs02.dfw /vicepa used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(divideSeries(stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.used, #A), 100)"
    }
   ]
  },
  {
   "title": "afs01.ord /vicepa used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(divideSeries(stats.gauges.afs.afs01_ord_openstack_org.part.vicepa.used, #A), 100)"
    }
   ]
  },
  {
   "title": "Usage history",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.part.vicepa.used, 'afs01.dfw')"
    },
    {
     "target": "alias(stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.used, 'afs02.dfw')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_ord_openstack_org.part.vicepa.used, 'afs01.ord')"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "afs01.dfw",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.calls_waiting, 'Calls Waiting')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.idle_threads, 'Idle Threads')"
    }
   ]
  },
  {
   "title": "afs02.dfw",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs02_dfw_openstack_org.calls_waiting, 'Calls Waiting')"
    },
    {
     "target": "alias(stats.gauges.afs.afs02_dfw_openstack_org.idle_threads, 'Idle Threads')"
    }
   ]
  },
  {
   "title": "afs01.ord",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_ord_openstack_org.calls_waiting, 'Calls Waiting')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_ord_openstack_org.idle_threads, 'Idle Threads')"
    }
   ]
  },
  {
   "title": "mirror-update.opendev.org mirror vos release timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume release timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.afs.release.mirror*.mean, 4)"
    }
   ]
  },
  {
   "title": "Mirror release times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mirror.centos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "mirror.centos-stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos-stream_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "mirror.fedora",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_fedora_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "mirror.epel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_epel_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "mirror.yum-puppetlabs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_yum-puppetlabs_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "Mirror volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mirror.centos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "mirror.centos-stream",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos-stream.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_centos-stream.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "mirror.fedora",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_fedora.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_fedora.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "mirror.epel",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_epel.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_epel.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "mirror.yum-puppetlabs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_yum-puppetlabs.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_yum-puppetlabs.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "mirror-update.opendev.org project vos release timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume release timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.afs.release.project*.mean, 4)"
    },
    {
     "target": "aliasByNode(stats.timers.afs.release.docs*.mean, 4)"
    }
   ]
  },
  {
   "title": "Wheel volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 8 Stream ARM64",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sa64.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sa64.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "Centos 9 Stream ARM64",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sa64.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sa64.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "Centos 7 x86_64",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent7x64.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent7x64.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "Centos 8 Stream x86_64",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sx64.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sx64.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "Centos 9 Stream x86_64",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sx64.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sx64.quota, 'Quota')"
    }
   ]
  },
  {
   "title": "Wheel release timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Centos 8 Stream ARM64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sa64_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "Centos 9 Stream ARM64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sa64_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "Centos 7 x86_64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent7x64_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "Centos 8 Stream x86_64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent8sx64_readonly.creation, 1000)"
    }
   ]
  },
  {
   "title": "Centos 9 Stream x86_64",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "scale(stats.gauges.afs.afs01_dfw_openstack_org.vol.mirror_wheel_cent9sx64_readonly.creation, 1000)"
    }
   ]
  }
 ]
}