{
 "title": "RDO Trunk build metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Today's RDO Trunk stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RDO Trunk total builds for today",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dlrn_metrics_total", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "RDO Trunk successful builds for today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dlrn_metrics_succeeed", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "RDO Trunk failed builds for today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dlrn_metrics_failed", "legendFormat": "{{worker}}" }
   ]
  },
  { "title": "Daily RDO trunk stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total RDO Trunk builds",
   "type": "graph",
   "description": "Number of total RDO Trunk builds, per worker",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dlrn_metrics_total", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "Successful RDO Trunk builds",
   "type": "graph",
   "description": "Number of successful RDO Trunk builds, per worker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dlrn_metrics_succeeed", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "Failed RDO Trunk builds",
   "type": "graph",
   "description": "Number of failed RDO Trunk builds, per worker",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dlrn_metrics_failed", "legendFormat": "{{worker}}" }
   ]
  }
 ]
}