---
- name: Get content for provided ssh key path
  when: ssh_pub_path is defined and ssh_pub_path
  block:
    - name: Check if provided ssh key exists
      ansible.builtin.stat:
        path: "{{ ssh_pub_path }}"
      register: _ssh_pub_path_stat

    - name: Fail when key does not exists
      ansible.builtin.fail:
        msg: "Provided {{ ssh_pub_path }} does not exists!"
      when: not _ssh_pub_path_stat.stat.exists

    - name: Read public key if ssh_pub not provided
      ansible.builtin.command: cat {{ ssh_pub_path }}
      register: _ssh_pub_path_key

- name: "Create {{ vm_name }} VM base on image {{ image_name | default(base_image.stdout) }} on cloud {{ cloud_name }}"
  register: _vm_status
  until: |
    "'details' in _vm_status.extra_data and 'Quota exceeded' not in _vm_status.extra_data.details"
  retries: 10
  delay: 60
  openstack.cloud.server:
    state: present
    cloud: "{{ cloud_name }}"
    name: "{{ vm_name }}"
    image: "{{ image_name | default(base_image.stdout) }}"
    key_name: "{{ ssh_keypair_name }}"
    timeout: 900
    flavor: "{{ flavor }}"
    nics:
      - net-id: "{{ net_id }}"
    meta:
      hostname: crc.dev
    wait: true
    config_drive: true
    security_groups:
      - default
    # Add image-builder pub key to the remote host.
    # It will inject via cloud-init a host SSH pub key to have access
    # to deploy the CRC instead of adding new SSH ke via virt-customize.
    userdata: |
      #cloud-config
      users:
        - default
        - name: "{{ image_ssh_user | default('zuul') }}"
          ssh_authorized_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdBiYfRpZCEOFGkVcorTs9R+JfP6LVCVmeaQVnDINTwZA/J9LJmsKjJA6iTgzV7YBJM8dM4J/yBSUoZMFvxs9Vy5RvCmSlOBsXsX1IY7KvfjB9ZdoFT5YLvPYxHiYWcaov0poGMu8kyHbzyV/LKfuC82X7C5Oo6cf6hK7ERb0HKmEIVZ+4A6y0einVPc6ByuavgUBwlsUXNyYMnkZZnqL5qmVJImL0etrblOwrW4o9U/MxNb9Q6gpvyYKf/rjt+cjGnRzOufJ+Gpt2NGyqfEIF1qgjxMPAOkeFl+mkUnHNJJac+9wQIEWAQFSUUdCSKMMHXPPTF3GB+Jkx9AfO7fFfjCpa48oPCUDLL1FJ90SOSaR95cfAlree7dbChMffDMI9xumQjBaFn+DDCiFCQHVx49W4oUHEGSvXZOF4V2BsIxi9q1otX+9LplZ9WJ9dvsi5CgbXrIld42MruwHnTrGEaShv5FECjaC70A0CdHngGTwPFheaSq1MuTjJmzW0T89LeY1XTFizUA9DM+gQnzZH5QmmYgYjM7IwSxSZydZA1SIJMq1LAOYEpug8sQ0hP7hHkZ7U9I/aUs5U0GSrcw4LPNgM7MOq4Q+NadPwA4raLUlj4CliSav0oX1LusEFG+dnfNIsoPoWrtr2X2tc6ZeWU1BncGfxYf/WrWEkZcSz8w== zuul@us"
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1Mog8QY/46KUC3OqOjdHG/UO/fkNTD3UwRLCDaFjAuF8kdGa7zKasppyZpo3sOt5yhsS+G2M0DObPfYfBWqi39jmlEnLioaLjn/xFLXpml2CK8d32NIK+K0AzxYiI96g6s8yCK1UtlTizNwnMhaY5OtyXeW8WRUJhcwuPLrgck6kw5kMtf0SOgBqCa4qSdH8F+k0Hj28iilmDXAvCd4BfLBdUE45tTj54fXKMHC4FOmYz2n/iSWQec6x4yoec5bi5fiCt1y93bs/QcQEGgW6tJx/5OufFcwX6ufDkPGHZQRN5IxuuGwU0Rgdw19sBi2srlqIkUfmfr4aWR1PQ9ASBy8U2mEjZYb86Xsd/X7C0IqSZxawu97sVwzw5XKBHW3n9nvwegEzmzg6xoER1Q1AxHl0Zv/nb7ak5Us8YhH/Rt/Aosv9xe7lkl3obpqOty8WzRD2ghUzTrposOJ/ApEBQXtJ4YYUSk8t9jP5+d6lgw90gW1BBItUklktgPzzHjJ8TLKXU4eQzxVvtL8NHRfTLcLU/XnPyyPUb26boFOqxebhEx06cyCVRxJBLO3jOjiyPpfkp9vWkzksfRvX8UTi1r1CxjqBIKTiDamM98Znp81NgUz1pojNm+J2p9uJ8zX87ybVQXnW3ZAr8EgTeldZJBrj22geQS8kpCWAdRuwniQ== zuul@ds"
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIppNzjGx/3nYeinqak/o9UYgtC42kymxv/s3SxVXbJ3 centos@image-builder.sf.hosted.upshift.rdu2.redhat.com next-gen@ds"
