{
 "title": "Openstack Upstream Releases Promotions",
 "description": "List of Zuul Jobs under different upstream Openstack releases promotion pipelines",
 "tags": [ "zuul-jobs-upstream-promotions" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pipeline: openstack-periodic-container-master-centos9 jobs zuul jobs",
   "type": "table",
   "description": "Jobs under the Pipeline: openstack-periodic-container-master-centos9 jobs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-master-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-periodic-container-master-centos9 jobs Chart",
   "type": "piechart",
   "description": "Jobs under the Pipeline: openstack-promote-component jobs chart percents",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-master-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-periodic-container-master-centos9 jobs Gauge",
   "type": "gauge",
   "description": "Jobs under the Pipeline: openstack-periodic-container-master-centos9 jobs gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-master-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-periodic-container-antelope-centos9 jobs zuul jobs",
   "type": "table",
   "description": "Jobs under the Pipeline: openstack-periodic-container-antelope-centos9 jobs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-periodic-container-antelope-centos9 jobs Chart",
   "type": "piechart",
   "description": "Jobs under the Pipeline: openstack-promote-component jobs chart percents",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-periodic-container-antelope-centos9 jobs Gauge",
   "type": "gauge",
   "description": "Jobs under the Pipeline: openstack-periodic-container-antelope-centos9 jobs gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-periodic-container-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-operators-periodic-integration-antelope-centos9 jobs zuul jobs",
   "type": "table",
   "description": "Jobs under the Pipeline: openstack-operators-periodic-integration-antelope-centos9 jobs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-operators-periodic-integration-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-operators-periodic-integration-antelope-centos9 jobs Chart",
   "type": "piechart",
   "description": "Jobs under the Pipeline: openstack-promote-component jobs chart percents",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-operators-periodic-integration-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pipeline: openstack-operators-periodic-integration-antelope-centos9 jobs Gauge",
   "type": "gauge",
   "description": "Jobs under the Pipeline: openstack-operators-periodic-integration-antelope-centos9 jobs gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "pipeline.keyword: \"openstack-operators-periodic-integration-antelope-centos9\" AND build_type: \"build\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}