{
 "title": "EOD - BackStage",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zuul Builds Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "result.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Users Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job) (increase(http_request[10m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg by (job) (increase(query{job=\"monocle\"}[10m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg by (job) (increase(http_request_error[10m]))",
     "legendFormat": "{{job}} error"
    }
   ]
  },
  {
   "title": "Runtime Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job) (ghc_gcdetails_live_bytes)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg by (job) (process_resident_memory_bytes{job=~\"logjuicer|logscraper\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Runtime CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (job) (rate(ghc_cpu_seconds_total[10m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg by (job) (rate(process_cpu_seconds_total{job=~\"logjuicer|logscraper\"}[10m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Systems", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemFree_bytes{instance=~\"zs.softwarefactory-project.io:9100|managesf.softwarefactory-project.io:9100|managesf.review.rdoproject.org:9100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Disk (max 10 GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "clamp_max(avg by(instance) (node_filesystem_avail_bytes{instance=~\"zs.softwarefactory-project.io:9100|managesf.softwarefactory-project.io:9100|managesf.review.rdoproject.org:9100\", mountpoint=\"/\"}), 10737418240)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "clamp_max(avg by(instance) (node_filesystem_avail_bytes{instance=\"logserver.rdoproject.org:9100\", mountpoint=\"/var/www/logs\"}), 10737418240)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "clamp_max(avg by(instance) (node_filesystem_avail_bytes{instance=\"elk.softwarefactory-project.io:9100\", mountpoint=\"/mnt\"}), 10737418240)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Load (recv are positive, sent are negative)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"zs.softwarefactory-project.io:9100|managesf.softwarefactory-project.io:9100|managesf.review.rdoproject.org:9100\", device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"zs.softwarefactory-project.io:9100|managesf.softwarefactory-project.io:9100|managesf.review.rdoproject.org:9100\", device=\"eth0\"}[$__rate_interval])*(-8)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=~\"system|user\",instance=~\"zs.softwarefactory-project.io:9100|managesf.softwarefactory-project.io:9100|managesf.review.rdoproject.org:9100\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Nodepool Launcher", "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes (in in-use state) by providers only available for centosinfra-prod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodepool_provider_nodes{softwarefactory=\"centosinfra-prod\", state=\"in-use\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Nodes (in hold state) by providers only available for centosinfra-prod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodepool_provider_nodes{softwarefactory=\"centosinfra-prod\", state=\"hold\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Instances spawned on the provider",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zuul_instances_total{ cloud=~\"vexxhost-nodepool.*\"}",
     "legendFormat": "{{cloud}}"
    }
   ]
  },
  {
   "title": "Total vCPU used by providers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zuul_instances_cpu{ cloud=~\"vexxhost-nodepool.*\"}",
     "legendFormat": "{{cloud}}"
    }
   ]
  },
  {
   "title": "Total Memory used by providers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "zuul_instances_mem{ cloud=~\"vexxhost-nodepool.*\"}",
     "legendFormat": "{{cloud}}"
    }
   ]
  },
  {
   "title": "Nodes (in failed state) by providers only available for centosinfra-prod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodepool_provider_nodes{softwarefactory=\"centosinfra-prod\", state=\"failed\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Amount of API calls error by providers (provided via zuul-capacity) / There will be no data if no errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "zuul_provider_error", "legendFormat": "{{cloud}}" }
   ]
  }
 ]
}