{
 "title": "RDO Puppet Promotions Pipeline",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Dalmatian promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*dalmatian* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  },
  {
   "title": "Caracal promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*caracal* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  },
  {
   "title": "Bobcat promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*bobcat* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  },
  {
   "title": "Antelope promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*antelope* AND -build_name:*periodic* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  },
  {
   "title": "Zed promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 44 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*zed* -build_name:*periodic* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  },
  {
   "title": "Yoga C9s promotions",
   "type": "table",
   "description": "Description",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 55 },
   "targets": [
    {
     "metrics": [
      {
       "settings": {
        "order": "desc",
        "size": "9000",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "build_queue:openstack-periodic-daily AND project:rdoinfo AND build_name:*yoga* AND build_name:\"*centos-stream-9\" AND -build_name:*periodic* AND message:\"*Job console starting\"",
     "timeField": "@timestamp",
     "timeFrom": "5d"
    }
   ]
  }
 ]
}