{
 "title": "Prow jobs operator success rate",
 "description": "Prow job success rate for OSP operators.",
 "tags": [ "prow-success" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prow operators ci-framework",
   "type": "stat",
   "description": "Prow job operators success rate ci-framework",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ci-framework-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ci-framework-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators cinder-operator",
   "type": "stat",
   "description": "Prow job operators success rate cinder-operator",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-cinder-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-cinder-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators dataplane-operator",
   "type": "stat",
   "description": "Prow job operators success rate dataplane-operator",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-dataplane-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-dataplane-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators edpm-ansible",
   "type": "stat",
   "description": "Prow job operators success rate edpm-ansible",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-edpm-ansible-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-edpm-ansible-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators glance-operator",
   "type": "stat",
   "description": "Prow job operators success rate glance-operator",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-glance-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-glance-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators horizon-operator",
   "type": "stat",
   "description": "Prow job operators success rate horizon-operator",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-horizon-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-horizon-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators infra-operator",
   "type": "stat",
   "description": "Prow job operators success rate infra-operator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-infra-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-infra-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators install_yamls",
   "type": "stat",
   "description": "Prow job operators success rate install_yamls",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-install_yamls-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-install_yamls-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators ironic-operator",
   "type": "stat",
   "description": "Prow job operators success rate ironic-operator",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ironic-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ironic-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators keystone-operator",
   "type": "stat",
   "description": "Prow job operators success rate keystone-operator",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-keystone-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-keystone-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators manila-operator",
   "type": "stat",
   "description": "Prow job operators success rate manila-operator",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-manila-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-manila-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators mariadb-operator",
   "type": "stat",
   "description": "Prow job operators success rate mariadb-operator",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-mariadb-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-mariadb-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators neutron-operator",
   "type": "stat",
   "description": "Prow job operators success rate neutron-operator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-neutron-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-neutron-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators nova-operator",
   "type": "stat",
   "description": "Prow job operators success rate nova-operator",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-nova-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-nova-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators octavia-operator",
   "type": "stat",
   "description": "Prow job operators success rate octavia-operator",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-octavia-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-octavia-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators openstack-ansibleee-operator",
   "type": "stat",
   "description": "Prow job operators success rate openstack-ansibleee-operator",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators openstack-baremetal-operator",
   "type": "stat",
   "description": "Prow job operators success rate openstack-baremetal-operator",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-baremetal-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-baremetal-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators openstack-operator",
   "type": "stat",
   "description": "Prow job operators success rate openstack-operator",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-openstack-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators osp-director-operator",
   "type": "stat",
   "description": "Prow job operators success rate osp-director-operator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-osp-director-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-osp-director-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators ovn-operator",
   "type": "stat",
   "description": "Prow job operators success rate ovn-operator",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ovn-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-ovn-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators placement-operator",
   "type": "stat",
   "description": "Prow job operators success rate placement-operator",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-placement-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-placement-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  },
  {
   "title": "Prow operators telemetry-operator",
   "type": "stat",
   "description": "Prow job operators success rate telemetry-operator",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-telemetry-operator-.*\", state=~\"success\"}[8h]))/sum(rate(prowjobs{job_name=~\"pull-ci-openstack-k8s-operators-telemetry-operator-.*\", state=~\"success|aborted|failure\"}[8h]))*100"
    }
   ]
  }
 ]
}