{
 "title": "RDO Trunk Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total builds by worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dlrn_builds_total{instance=\"centos9-master-uc\"}",
     "legendFormat": "centos9-master-uc"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos9-xena\"}",
     "legendFormat": "centos9-xena"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos9-wallaby\"}",
     "legendFormat": "centos9-wallaby"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos9-yoga\"}",
     "legendFormat": "centos9-yoga"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-yoga\"}",
     "legendFormat": "centos8-yoga"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-xena\"}",
     "legendFormat": "centos8-xena"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-wallaby\"}",
     "legendFormat": "centos8-wallaby"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-victoria\"}",
     "legendFormat": "centos8-victoria"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-ussuri\"}",
     "legendFormat": "centos8-ussuri"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos8-train\"}",
     "legendFormat": "centos8-train"
    },
    {
     "expr": "dlrn_builds_total{instance=\"centos-train\"}",
     "legendFormat": "centos-train"
    }
   ]
  },
  {
   "title": "Total builds in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos9-master-uc\"}[24h])",
     "legendFormat": "centos9-master-uc"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos9-xena\"}[24h])",
     "legendFormat": "centos9-xena"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos9-wallaby\"}[24h])",
     "legendFormat": "centos9-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos9-yoga\"}[24h])",
     "legendFormat": "centos9-yoga"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-yoga\"}[24h])",
     "legendFormat": "centos8-yoga"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-xena\"}[24h])",
     "legendFormat": "centos8-xena"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-wallaby\"}[24h])",
     "legendFormat": "centos8-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-victoria\"}[24h])",
     "legendFormat": "centos8-victoria"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-ussuri\"}[24h])",
     "legendFormat": "centos8-ussuri"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos8-train\"}[24h])",
     "legendFormat": "centos8-train"
    },
    {
     "expr": "increase(dlrn_builds_total{instance=\"centos-train\"}[24h])",
     "legendFormat": "centos-train"
    }
   ]
  },
  {
   "title": "Successful builds in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos9-master-uc\"}[24h])",
     "legendFormat": "centos9-master-uc"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos9-xena\"}[24h])",
     "legendFormat": "centos9-xena"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos9-wallaby\"}[24h])",
     "legendFormat": "centos9-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos9-yoga\"}[24h])",
     "legendFormat": "centos9-yoga"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-yoga\"}[24h])",
     "legendFormat": "centos8-yoga"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-xena\"}[24h])",
     "legendFormat": "centos8-xena"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-wallaby\"}[24h])",
     "legendFormat": "centos8-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-victoria\"}[24h])",
     "legendFormat": "centos8-victoria"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-ussuri\"}[24h])",
     "legendFormat": "centos8-ussuri"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos8-train\"}[24h])",
     "legendFormat": "centos8-train"
    },
    {
     "expr": "increase(dlrn_builds_succeeded_total{instance=\"centos-train\"}[24h])",
     "legendFormat": "centos-train"
    }
   ]
  },
  {
   "title": "Failed builds in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos9-master-uc\"}[24h])",
     "legendFormat": "centos9-master-uc"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos9-xena\"}[24h])",
     "legendFormat": "centos9-xena"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos9-wallaby\"}[24h])",
     "legendFormat": "centos9-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos9-yoga\"}[24h])",
     "legendFormat": "centos9-yoga"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-yoga\"}[24h])",
     "legendFormat": "centos8-yoga"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-xena\"}[24h])",
     "legendFormat": "centos8-xena"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-wallaby\"}[24h])",
     "legendFormat": "centos8-wallaby"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-victoria\"}[24h])",
     "legendFormat": "centos8-victoria"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-ussuri\"}[24h])",
     "legendFormat": "centos8-ussuri"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos8-train\"}[24h])",
     "legendFormat": "centos8-train"
    },
    {
     "expr": "increase(dlrn_builds_failed_total{instance=\"centos-train\"}[24h])",
     "legendFormat": "centos-train"
    }
   ]
  }
 ]
}