all:
  children:
    OSEv3:
      children:
        etcd: {}
        installer: {}
        masters: {}
        nodes: {}
    afs-mirror:
      hosts:
        mirror.regionone.vexxhost.rdoproject.org: {}
    backup-rdo:
      hosts:
        managesf.review.rdoproject.org: {}
    backup-server:
      hosts:
        backup.rdoproject.org: {}
    backup-sf:
      hosts:
        ansible.softwarefactory-project.io: {}
        managesf.softwarefactory-project.io: {}
    bridge:
      hosts:
        bridge.softwarefactory-project.io: {}
    centos-infra-zuul-executors:
      hosts:
        microshift-ze01.softwarefactory-project.io: {}
        microshift-ze02.softwarefactory-project.io: {}
        microshift-ze03.softwarefactory-project.io: {}
        microshift-ze04.softwarefactory-project.io: {}
        microshift-ze05.softwarefactory-project.io: {}
    db_master:
      hosts:
        dlrn-db-centos9.rdoproject.org: {}
    dlrn-trunk:
      hosts:
        dlrn-db-centos9.rdoproject.org: {}
        trunk-builder-centos9.rdoproject.org: {}
        trunk-server-centos9.rdoproject.org: {}
    epel:
      hosts:
        k1s03.softwarefactory-project.io: {}
        k1s04.softwarefactory-project.io: {}
        k1s05.softwarefactory-project.io: {}
        k1s06.softwarefactory-project.io: {}
        sf-container-worker-1.softwarefactory-project.io: {}
    install-server:
      hosts:
        managesf-dev.softwarefactory-project.io: {}
        managesf.review.rdoproject.org: {}
        managesf.softwarefactory-project.io: {}
    k1s-rhel:
      hosts:
        k1s03.softwarefactory-project.io: {}
        k1s04.softwarefactory-project.io: {}
        k1s05.softwarefactory-project.io: {}
        k1s06.softwarefactory-project.io: {}
        sf-container-worker-1.softwarefactory-project.io: {}
    k1s-secrets:
      hosts:
        bridge.softwarefactory-project.io: {}
        k1s03.softwarefactory-project.io: {}
        k1s04.softwarefactory-project.io: {}
        k1s05.softwarefactory-project.io: {}
        k1s06.softwarefactory-project.io: {}
        sf-container-worker-1.softwarefactory-project.io: {}
    monitoring:
      hosts:
        monitoring.softwarefactory-project.io: {}
    observability-stack:
      hosts:
        bridge.softwarefactory-project.io: {}
    opensearch:
      hosts:
        opensearch.rdoproject.org: {}
    openstack:
      hosts:
        logscraper02.openstack.org: {}
    osci:
      hosts:
        lists.rdoproject.org: {}
    osci_zone:
      children:
        osci_internal_zone: {}
      hosts:
        lists.rdoproject.org: {}
    promtail:
      hosts:
        bridge.softwarefactory-project.io: {}
        elk.softwarefactory-project.io: {}
        image-builder.softwarefactory-project.io: {}
        k1s03.softwarefactory-project.io: {}
        k1s04.softwarefactory-project.io: {}
        k1s05.softwarefactory-project.io: {}
        k1s06.softwarefactory-project.io: {}
        managesf.softwarefactory-project.io: {}
        microshift-infra.softwarefactory-project.io: {}
        microshift-ze01.softwarefactory-project.io: {}
        microshift-ze02.softwarefactory-project.io: {}
        microshift-ze03.softwarefactory-project.io: {}
        microshift-ze04.softwarefactory-project.io: {}
        microshift-ze05.softwarefactory-project.io: {}
        sf-container-worker-1.softwarefactory-project.io: {}
        zk01.softwarefactory-project.io: {}
        zs.softwarefactory-project.io: {}
    promtail-openshift:
      hosts:
        microshift-infra.softwarefactory-project.io: {}
    quay:
      hosts:
        quay.rdoproject.org: {}
    rdo:
      hosts:
        backup.rdoproject.org: {}
        dlrn-db-centos9.rdoproject.org: {}
        logserver.rdoproject.org: {}
        managesf.review.rdoproject.org: {}
        mirror.regionone.vexxhost.rdoproject.org: {}
        opensearch.rdoproject.org: {}
        quay.rdoproject.org: {}
        trunk-builder-centos9.rdoproject.org: {}
        trunk-server-centos9.rdoproject.org: {}
    rhel:
      hosts:
        ansible.softwarefactory-project.io: {}
        backup.rdoproject.org: {}
        bridge.softwarefactory-project.io: {}
        dlrn-db-centos9.rdoproject.org: {}
        elk.softwarefactory-project.io: {}
        image-builder.softwarefactory-project.io: {}
        k1s03.softwarefactory-project.io: {}
        k1s04.softwarefactory-project.io: {}
        k1s05.softwarefactory-project.io: {}
        k1s06.softwarefactory-project.io: {}
        logserver.rdoproject.org: {}
        managesf-dev.softwarefactory-project.io: {}
        managesf.review.rdoproject.org: {}
        managesf.softwarefactory-project.io: {}
        microshift-ze01.softwarefactory-project.io: {}
        microshift-ze02.softwarefactory-project.io: {}
        microshift-ze03.softwarefactory-project.io: {}
        microshift-ze04.softwarefactory-project.io: {}
        microshift-ze05.softwarefactory-project.io: {}
        mirror.regionone.vexxhost.rdoproject.org: {}
        monitoring.softwarefactory-project.io: {}
        opensearch.rdoproject.org: {}
        quay.rdoproject.org: {}
        sf-container-worker-1.softwarefactory-project.io: {}
        trunk-builder-centos9.rdoproject.org: {}
        trunk-server-centos9.rdoproject.org: {}
        zk01.softwarefactory-project.io: {}
        zs.softwarefactory-project.io: {}
    sf:
      hosts:
        ansible.softwarefactory-project.io: {}
        elk.softwarefactory-project.io: {}
        image-builder.softwarefactory-project.io: {}
        managesf-dev.softwarefactory-project.io: {}
        managesf.softwarefactory-project.io: {}
        zk01.softwarefactory-project.io: {}
        zs.softwarefactory-project.io: {}
    sf-operator:
      hosts:
        bridge.softwarefactory-project.io: {}
        microshift-ze01.softwarefactory-project.io: {}
        microshift-ze02.softwarefactory-project.io: {}
        microshift-ze03.softwarefactory-project.io: {}
        microshift-ze04.softwarefactory-project.io: {}
        microshift-ze05.softwarefactory-project.io: {}
  hosts:
    ansible.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    backup.rdoproject.org:
      ansible_host: '52.71.149.221'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: ec2-user
    bridge.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    dlrn-db-centos9.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    elk.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    image-builder.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    k1s03.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    k1s04.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    k1s05.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    k1s06.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    lists.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: root
    logscraper02.openstack.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: sf
    logserver.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    managesf-dev.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    managesf.review.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    managesf.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-infra.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-ze01.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-ze02.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-ze03.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-ze04.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    microshift-ze05.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    mirror.regionone.vexxhost.rdoproject.org:
      ansible_host: '38.102.83.237'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    monitoring.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    opensearch.rdoproject.org:
      ansible_host: '38.102.83.14'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    quay.rdoproject.org:
      ansible_host: '38.102.83.197'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    sf-container-worker-1.softwarefactory-project.io:
      ansible_host: '38.129.16.117'
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    trunk-builder-centos9.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    trunk-server-centos9.rdoproject.org:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    zk01.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
    zs.softwarefactory-project.io:
      ansible_port: 22
      ansible_python_interpreter: auto
      ansible_user: cloud-user
