{
 "title": "Resource Metrics  - vexxhost",
 "description": "Ported dashboard from http://rhos-ci-monitoring.lab.eng.tlv2.redhat.com/",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resource", "label": "Resource", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "resource name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$resource\",job=\"node-exporter\"} or up{instance=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "shortname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$resource\",job=\"node-exporter\",instance_short!=\"\"}"
    }
   ]
  },
  {
   "title": "site",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$resource\",job=\"node-exporter\"} or up{instance=~\"$resource\",job=\"ping-exporter\"} or up{instance=~\"$resource\",job=\"blackbox\"} "
    }
   ]
  },
  {
   "title": "tier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$resource\",job=\"node-exporter\"} or up{instance=~\"$resource\",job=\"ping-exporter\"} or up{instance=~\"$resource\",job=\"blackbox\"} "
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$resource\"} - node_boot_time_seconds{instance=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$resource\"}) without (mode,job,service,site)) without (cpu)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$resource\"}) without (job,service,site)"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$resource\"}"
    }
   ]
  },
  {
   "title": "n-exporter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{instance=~\"$resource\"}"
    }
   ]
  },
  {
   "title": "marked 'is_offline' in the inventory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$resource\",job=\"node-exporter\",instance_short!=\"\"}"
    }
   ]
  },
  {
   "title": "offline reason",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$resource\",job=\"node-exporter\",instance_short!=\"\"}"
    }
   ]
  },
  {
   "title": "kernel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{instance=~\"$resource\"}) by (env,instance,machine,release)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=~\"$resource\",device!=\"rootfs\"}  - node_filesystem_avail_bytes{instance=~\"$resource\"} ) / node_filesystem_size_bytes{instance=~\"$resource\"} ) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Monitoring ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$resource\"}",
     "legendFormat": "{{job}} {{target}}"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "LOAD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$resource\"} ",
     "legendFormat": "Load 1"
    },
    {
     "expr": "node_load5{instance=~\"$resource\"} ",
     "legendFormat": "Load 5"
    },
    {
     "expr": "node_load15{instance=~\"$resource\"} ",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "graph",
   "description": "Used CPU from a total available of 100%.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$resource\"}[3m])) * 100) ",
     "legendFormat": "CPU utilization"
    },
    {
     "expr": "(avg by(instance) (irate(node_cpu_seconds_total{mode=\"steal\",instance=~\"$resource\"}[3m])) * 100) ",
     "legendFormat": "Stolen by the host"
    }
   ]
  },
  {
   "title": "CPU Individual Cores Used",
   "type": "graph",
   "description": "Used CPU from a total available of 100%.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance, cpu) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$resource\"}[3m])) * 100) ",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "MEMORY Available/Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$resource\"} ",
     "legendFormat": "MemAvailable"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$resource\"} / node_memory_MemTotal_bytes{instance=\"$resource\"}",
     "legendFormat": "% MemAvailable "
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$resource\"} ",
     "legendFormat": "MemFree"
    }
   ]
  },
  {
   "title": "MEMORY Usage ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$resource\"} ",
     "legendFormat": "buff"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$resource\"} ",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$resource\"} ",
     "legendFormat": "swapcached"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$resource\"} ",
     "legendFormat": "slab"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$resource\"} ",
     "legendFormat": "pagetables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=\"$resource\"} ",
     "legendFormat": "vmalloc"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$resource\"} - node_memory_SwapFree_bytes{instance=\"$resource\"}) / node_memory_SwapTotal_bytes{instance=\"$resource\"}) * 100",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Filesystem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FILESYSTEM Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=~\"$resource\"}  - node_filesystem_avail_bytes{instance=~\"$resource\"} ) / node_filesystem_size_bytes{instance=~\"$resource\"} ) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOPs, Reads, Writes",
   "type": "graph",
   "description": "Reads + Writes = Total.\n- Critical:\n  - If > 500 iops then there is a High Load.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, env) (rate(node_disk_reads_completed_total{instance=~\"$resource\"}[3m]) + rate(node_disk_writes_completed_total{instance=~\"$resource\"}[3m]))",
     "legendFormat": "IOPs"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$resource\"}[3m])",
     "legendFormat": "{{device}} - bytes written"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$resource\"}[3m])",
     "legendFormat": "{{device}} - bytes read"
    }
   ]
  },
  {
   "title": "DISK RW Latency",
   "type": "graph",
   "description": "DISK seconds Read/ Write Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{instance=~\"$resource\"}[3m])/ rate(node_disk_reads_completed_total{instance=~\"$resource\"}[3m])) ",
     "legendFormat": "{{device}} - read latency"
    },
    {
     "expr": "(rate(node_disk_write_time_seconds_total{instance=~\"$resource\"}[3m])/ rate(node_disk_writes_completed_total{instance=~\"$resource\"}[3m])) ",
     "legendFormat": "{{device}}  - write latency"
    }
   ]
  },
  {
   "title": "FILESYSTEM Inodes Used",
   "type": "graph",
   "description": "Filesystem used file nodes.\n> If is > 85% the is Critical.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_files{instance=~\"$resource\"} - node_filesystem_files_free{instance=~\"$resource\"}) / node_filesystem_files{instance=~\"$resource\"}) * 100",
     "legendFormat": "{{device}} on {{mountpoint}} type {{fstype}}  - Filesystem Inodes "
    }
   ]
  },
  {
   "title": "FILE DESCRIPTORS Used",
   "type": "graph",
   "description": "Used FILE DESCRIPTORS from a total available of 100%.\n- FILE DESCRIPTORS Threshold:\n >Critical: > 90% Used FILE DESCRIPTORS",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(node_filefd_allocated{instance=~\"$resource\"} / node_filefd_maximum{instance=~\"$resource\"}) * 100",
     "legendFormat": "File Descriptors Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "FILESYSTEM Device Error",
   "type": "graph",
   "description": "Whether an error occurred while getting statistics for the given device.\n> A value > 0 Means that there are some problems with that device.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_device_error{instance=~\"$resource\"} ",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NETWORK INTERFACE State",
   "type": "graph",
   "description": "- Valid operstate for interface.\n  - UP = 1\n  - DOWN = 0",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_network_up{instance=~\"$resource\",interface!=\"lo\",interface!~\"vnet.*|.*(management|external|data|virbr).*\"} ",
     "legendFormat": "Network Interface State: {{instance}} {{interface}} {{operstate}}"
    }
   ]
  },
  {
   "title": "NETWORK IN/OUT Traffic",
   "type": "graph",
   "description": "IN/ OUT Traffic rate.\n- Critical:\n  - If IN/OUT traffic = 0% from a total of 100% possible on that interface there is Low Bandwidth or interface problem.\n  - If IN/OUT traffic > 95% from a total of 100% possible on that interface there is High Bandwidth.\n\n95% (0.95 x 1e+09 =0.95 x 1 x 10^9 = 0.884756 GB, Gigabytes) supposing that the interface is 1 GB.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) * 8",
     "legendFormat": "IN: {{ device }}: {{instance}} ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) * -1 * 8",
     "legendFormat": "OUT: {{ device }}: {{instance}} ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "NETWORK IN/OUT Packets",
   "type": "graph",
   "description": "Network Packets for IN/OUT.\n- Critical:\n   - If  is = 0 for IN/OUT.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_packets_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m])",
     "legendFormat": "IN: {{device}}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_packets_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) * -1",
     "legendFormat": "OUT: {{device}}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "NETWORK IN/OUT Drops",
   "type": "graph",
   "description": "Network Drops.\n- Critical:\n   - If  is > 0 then are Drops on that interface (IN/OUT) and is not ok.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_drop_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) ",
     "legendFormat": "IN: {{device}}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_drop_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) ",
     "legendFormat": "OUT: {{device}}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "NETWORK IN/OUT Errors",
   "type": "graph",
   "description": "Network Errors on IN/OUT.\n- Critical:\n  - If Errors > 0 then there are some problems on that interface.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Errors /s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_errs_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) ",
     "legendFormat": "IN: {{ device }}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_errs_total{instance=~\"$resource\", device!=\"lo\",device!~\"vnet.*|.*(management|external|data|virbr).*\"}[3m]) ",
     "legendFormat": "OUT: {{ device }}: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Virt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PROCESSES FILE DESCRIPTORS Used",
   "type": "graph",
   "description": "Processes used File Descriptors.\n- Critical:\n   - If > 85% then there is High Usage.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{instance=~\"$resource\"} / process_max_fds{instance=~\"$resource\"}) * 100",
     "legendFormat": "Process Used File Descriptors: {{instance}}"
    }
   ]
  },
  {
   "title": "NTP Offset in Seconds",
   "type": "graph",
   "description": "Time offset in between local system and reference clock.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_timex_offset_seconds{instance=~\"$resource\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NTP Sync Status",
   "type": "graph",
   "description": "0/1 based on if considered in sync",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=~\"$resource\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ENTROPY",
   "type": "graph",
   "description": "Bits of available entropy.\n- Critical:\n  - If < 500 there is a problem.\nThe following command will tell you the available entropy in your system:\n\n$ cat /proc/sys/kernel/random/entropy_avail\nThe consensus is that numbers below 1000 will lead to processes blocking waiting for more entropy.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=~\"$resource\"}",
     "legendFormat": "Entropy: {{instance}}"
    }
   ]
  },
  {
   "title": "CONTEXT SWITCHES",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$resource\"}[$__range])",
     "legendFormat": "Context Switches: {{instance}}"
    }
   ]
  },
  {
   "title": "INTERRUPTS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_intr_total{instance=~\"$resource\"}[$__range])",
     "legendFormat": "Interrupts: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "FORKS",
   "type": "graph",
   "description": "Number of Forks.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks_total{instance=~\"$resource\"}[$__range]) ",
     "legendFormat": "Forks: {{instance}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}