- hosts: all
  tasks:
    - name: Install zuulclient
      become: true
      ansible.builtin.command: pip3 install zuul-client

    - name: Install ansible
      become: true
      ansible.builtin.dnf:
        name:
          - ansible-core
        state: present

    - name: Copy the vault password
      ansible.builtin.copy:
        content: "{{ vault.secret }}"
        dest: "~/.ansible_vault"
        mode: "0400"
      no_log: yes
      when: vault is defined

    - name: Validate the secrets
      ansible.builtin.shell: "python3 tools/rotate-ansible-vault-password.py --dry-run ~/.ansible_vault"
      args:
        chdir: "{{ zuul.project.src_dir }}"
